cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .m2
    - cyn-relationship-manager-video-client/target
    - cyn-relationship-manager-video-server/target

variables:
  SONAR_TOKEN: $SONAR_TOKEN
  SONAR_HOST_URL: $SONAR_HOST
  GIT_DEPTH: 0

stages:
  - mavenbuild

Maven Package 📦:
  stage: mavenbuild
  image: maven:3.6.3-jdk-11
  script:
    - mvn -s ci_settings.xml deploy verify sonar:sonar -Dsonar.qualitygate.wait=true
  only:
    - master
    - develop
