version: '3'

services:
  # MySQL
  db:
    container_name: mysql8
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
  openvidu-server:
    container_name: openvidu-server
    image: openvidu/openvidu-server-kms:2.16.0
    ports:
      - "4443:4443"
    environment:
      - openvidu.secret=MY_SECRET
