-- MySQL Script generated by MySQL Workbench
-- Fri Mar 19 10:32:59 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema RM_VIDEO_SERVICE
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `RM_VIDEO_SERVICE` DEFAULT CHARACTER SET utf8 ;
USE `RM_VIDEO_SERVICE` ;

-- -----------------------------------------------------
-- Table `RM_VIDEO_SERVICE`.`sessions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RM_VIDEO_SERVICE`.`sessions` ;

CREATE TABLE IF NOT EXISTS `RM_VIDEO_SERVICE`.`sessions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `appointments_id` INT NOT NULL,
  `session_id` VARCHAR(128) NOT NULL,
  `user_name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `session_id_UNIQUE` (`session_id` ASC) VISIBLE,
  UNIQUE INDEX `appointments_id_UNIQUE` (`appointments_id` ASC) VISIBLE 
)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
