version: '3.3'
services:
  db:
    image: mysql:8
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: RM_VIDEO_SERVICE
    ports:
      - "3306:3306"
    expose:
      - '3306'
  openvidu:
    image: openvidu/openvidu-server-kms
    ports:
      - "4443:4443"
    environment:
      OPENVIDU_SECRET: MY_SECRET
      OPENVIDU_WEBHOOK: 'true'
      OPENVIDU_WEBHOOK_ENDPOINT: 'http://host.docker.internal:8102/v1/conferencing/service/customer/rm/openvidu/webhook'
      OPENVIDU_WEBHOOK_HEADERS: '["Authorization: Bearer MY_API_TOKEN"]'
      OPENVIDU_WEBHOOK_EVENTS: '["sessionCreated","sessionDestroyed"]'
