FROM openjdk:11.0.7-jre-slim

WORKDIR /app

ADD ./target/cyn-relationship-manager-appointment-server-1.0.0-SNAPSHOT.jar /app

CMD  ["java", "-jar", "cyn-relationship-manager-appointment-server-1.0.0-SNAPSHOT.jar"]
